### ISSUE TITLE
Update Vulnerable Dependency

### ISSUE THREAD

**Issue by thealphadollar** [metakgp/batman#1]
As per github the following dependencies need to be updated and are currently vulnerable:

- requests
- pyopenssl
- urllib3

**Comment by berserker1** [comment]
Currently, they are
>pyOpenSSL==17.0.0
>requests==2.9.1
>urllib3==1.15.1

Will this change be suitable?
>pyOpenSSL>=17.0.0
>requests>=2.9.1
>urllib3>=1.15.1

**Comment by thealphadollar** [comment]
urllib3>=1.24.2
requests>=2.20.0
pyopenssl>=17.5.0

**Comment by berserker1** [comment]
Ok will do
